### ISSUE TITLE
[META] First cut

### ISSUE THREAD

**Issue by franklinchou** [franklinchou/inception#1]
# Non-dreaming/wakeful reality check

## Features:
- [ ] daily reminder While awake between certain hours to sound a "totem sound" defaults to 3 sounds/day
- [ ] Set waking hours and sleeping hours
- [ ] dreaming reality check/dream clues
- [ ] sound a totem at night to check dream state from w/n dreams (set sleeping hours and # of clues) Dream clues are controlled by media volume NOT notification volume. Set phone to silent (ringer off) but turn media all the way up to hear dream clues.

## Nice to have
- [ ] dream journal integration with google drive
- [ ] pausing
